version: '3.8'
services:
  backend-nest-js:
    build: ./backend-nest-js
    ports:
      - "3000:3000"
    volumes:
      - ./backend-nest-js:/backend-nest-js
  frontend-react-js:
    build: ./frontend-react-js
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react-js:/frontend-react-js
